---
title: "Assignment 1: Introduction"
author: "Sarah Sussman"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I don't have a ton of experience, which is why I wanted to take this class. I had never used R until this week in my statistics class. I used Git and learned python in John's Geospatial Data Analytics class last fall.

2. Are there any components of the course about which you feel confident?

> Answer: 
I feel confident in using Git. I always get nervous when it comes to more analytical/computer type work, but within the last 1.5 years at the Nicholas School I've become more confident in my ability to learn.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I feel apprehensive about using R since it is brand new to me, but I am also excited to learn it!

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/sarah-sussman/EDA_Spring2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
